server.port=8083

logging.level.org.springframework=info

logging.level.com.cognizant.spring_learn=debug
logging.level.com.cognizant.springlearn=debug

logging.pattern.console=%d{yyyyMMdd HH:mm:ss.SSS} %-20.20thread %-5level %logger{25} - %msg%n